"""v2_instructor_packages_system

Revision ID: ec9e2a3415ea
Revises: 002
Create Date: 2026-06-24 11:57:38.061924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9e2a3415ea'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_instructors_id'), 'instructors', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'discipline_id', 'instructor_id', name='uq_active_package')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.add_column('appointments', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('package_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'packages', ['package_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'instructors', ['instructor_id'], ['id'])
    op.add_column('availability_rules', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'availability_rules', 'instructors', ['instructor_id'], ['id'])
    op.add_column('blocked_dates', sa.Column('is_global', sa.Boolean(), nullable=False))
    op.add_column('disciplines', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.add_column('disciplines', sa.Column('slot_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('disciplines', sa.Column('active_from', sa.Date(), nullable=True))
    op.add_column('disciplines', sa.Column('active_until', sa.Date(), nullable=True))
    op.drop_constraint(op.f('disciplines_name_key'), 'disciplines', type_='unique')
    op.create_unique_constraint('uq_discipline_instructor', 'disciplines', ['name', 'instructor_id'])
    op.create_foreign_key(None, 'disciplines', 'instructors', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.drop_constraint('uq_discipline_instructor', 'disciplines', type_='unique')
    op.create_unique_constraint(op.f('disciplines_name_key'), 'disciplines', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('disciplines', 'active_until')
    op.drop_column('disciplines', 'active_from')
    op.drop_column('disciplines', 'slot_duration_minutes')
    op.drop_column('disciplines', 'instructor_id')
    op.drop_column('blocked_dates', 'is_global')
    op.drop_constraint(None, 'availability_rules', type_='foreignkey')
    op.drop_column('availability_rules', 'instructor_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'package_id')
    op.drop_column('appointments', 'instructor_id')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_instructors_id'), table_name='instructors')
    op.drop_table('instructors')
    # ### end Alembic commands ###
