"""instructor_email

Revision ID: edfa62d1ad24
Revises: ec9e2a3415ea
Create Date: 2026-06-24 14:55:00.756751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfa62d1ad24'
down_revision: Union[str, None] = 'ec9e2a3415ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'instructors', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructors', type_='unique')
    op.drop_column('instructors', 'email')
    # ### end Alembic commands ###
